version: '3.8'

services:
  metabase:
    image: jimchen2/jc-metabase-arm:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3829:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=your_hosted_db_name
      - MB_DB_PORT=your_hosted_db_port
      - MB_DB_USER=your_hosted_db_user
      - MB_DB_PASS=your_hosted_db_password
      - MB_DB_HOST=your_hosted_db_host
    restart: always
