version: '3.8'

services:
  metabase:
    image: jimchen2/jc-metabase-arm:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3829:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabasepassword
      - MB_DB_HOST=postgres
    depends_on:
      - postgres
    networks:
      - metabase-network
    restart: always

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabasepassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - metabase-network
    restart: always

networks:
  metabase-network:
    driver: bridge

volumes:
  postgres-data: